Use single CloudFormation object
KCOM-Enterprise/cfn-square pull request #24
Opened 2018-10-22 13:11 UTC by PaulBurridge-kcom

ParameterResolver was using a seperate CloudFormation object, as such clearing of the STACK_DESCRIPTIONS cache was taking place on a different object than that used to get the stack descriptions.

Fixed by passing the main instance of Cloudformation to the constructor of ParameterResolver.

2018-10-22 13:52 UTC, steveparker-1984 requested changes
Looks ok, but you'll need to increment the version (line 22) in build.py for it to release to pypi

2018-10-22 14:56 UTC, steveparker-1984 submitted a review, later dismissed

2018-10-22 15:03 UTC, steveparker-kcom commented
@PaulBurridge-kcom I think travis is stuck. Could you squash please? Might kick it back into gear

2018-10-26 06:18 UTC, rayhwang-kcom commented
What's the difference between magic mock and magic mock 2?

2018-10-29 11:23 UTC, PaulBurridge commented
There is no MagicMock2 do you mean unittest2?

https://pypi.org/project/unittest2/ "unittest2 is a backport of the new features added to the unittest testing framework in Python 2.7 and onwards. "

The preference for unittest2 with fallback to unittest was already in this file before I made my changes.

2018-10-29 12:16 UTC, rayhwang-kcom commented
It appears that I was on drugs when I wrote that... looks fine.

2018-10-29 12:16 UTC, rayoogmy approved these changes

2018-10-29 12:16 UTC, merged